spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.19.153.23:3306/netschool?characterEncoding=utf8

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.edu.hfut.net.netschool.model
server:
  port: 80
