spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://i.hjwblog.com:3306/netschool?characterEncoding=utf8

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.edu.hfut.net.netschool.model
server:
  port: 80
